import type { Metadata } from "next";
import Link from "next/link";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Terms and conditions governing the use of Prospect.",
};

export default function TermsOfUsePage() {
  return (
    <article className="mx-auto max-w-4xl space-y-10 py-2">
      {/* Header */}
      <header className="space-y-3 border-b border-slate-200 pb-6">
        <div className="inline-flex items-center gap-2 rounded bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-800 border border-amber-200">
          <span>Notice: Baseline Draft Pending Final Human Review</span>
        </div>
        <h1 className="text-3xl font-semibold tracking-tight text-slate-900">Terms of Use</h1>
        <p className="text-sm text-slate-600">
          Last updated: September 2026 · Please read these terms carefully before accessing or using
          the Prospect platform.
        </p>
      </header>

      {/* 1. Acceptance */}
      <section aria-labelledby="acceptance-heading" className="space-y-4">
        <h2 id="acceptance-heading" className="text-xl font-semibold text-slate-900">
          1. Acceptance of Terms
        </h2>
        <p className="text-sm leading-relaxed text-slate-700">
          By accessing or using the Prospect web application, uploading documents, or viewing
          extracted financial analyses, you agree to be bound by these Terms of Use and our{" "}
          <Link href="/privacy" className="text-slate-900 underline hover:text-slate-700">
            Privacy Policy
          </Link>
          . If you do not agree to these terms, you must not access the platform or upload any
          files.
        </p>
      </section>

      {/* 2. Description of Service */}
      <section aria-labelledby="service-heading" className="space-y-4">
        <h2 id="service-heading" className="text-xl font-semibold text-slate-900">
          2. Description of Service
        </h2>
        <p className="text-sm leading-relaxed text-slate-700">
          Prospect is a specialized financial document intelligence tool. It processes user-uploaded
          PDF documents (annual reports, financial statements, and prospectuses) to extract reported
          financial figures and compute mathematical financial ratios, linking each result directly
          to verbatim source evidence and page citations.
        </p>
        <p className="text-sm leading-relaxed text-slate-700">
          Prospect operates an anonymous, workspace-oriented model without mandatory user
          registration. Workspaces and uploaded documents are temporary and subject to automated
          retention policies.
        </p>
      </section>

      {/* 3. Non-Negotiable Financial Disclaimer */}
      <section
        aria-labelledby="financial-disclaimer-heading"
        className="rounded-lg border-2 border-slate-300 bg-slate-50 p-6 space-y-4"
      >
        <div className="flex items-center gap-2">
          <span className="rounded bg-slate-900 px-2 py-0.5 text-xs font-semibold uppercase text-white dark:text-slate-950">
            Mandatory Disclaimer
          </span>
          <h2 id="financial-disclaimer-heading" className="text-lg font-semibold text-slate-900">
            3. Financial Analysis &amp; Investment Disclaimer
          </h2>
        </div>
        <div className="space-y-3 text-sm leading-relaxed text-slate-700">
          <p>
            <strong>Informational and Research Purposes Only:</strong> Prospect is strictly an
            informational research and document processing tool. Nothing on this website or
            generated by the service constitutes:
          </p>
          <ul className="list-disc space-y-1 pl-5">
            <li>Investment, financial, legal, tax, or accounting advice;</li>
            <li>
              A recommendation, endorsement, or solicitation to buy, sell, or hold any security,
              financial product, or corporate instrument;
            </li>
            <li>
              A guarantee, prediction, or forecast of financial performance or market outcomes;
            </li>
            <li>Brokerage, trade execution, or custodial services.</li>
          </ul>
          <p>
            <strong>Original Documents Remain Authoritative:</strong> Extracted figures, ratios, and
            timeline views are derived programmatically and may contain discrepancies or omissions.
            The original official regulatory filing, certified audit report, or published financial
            statement remains the sole authoritative source of truth. Users must independently
            verify all material data against original source filings before making investment or
            financial decisions.
          </p>
        </div>
      </section>

      {/* 4. Accuracy & Technical Quality */}
      <section aria-labelledby="accuracy-heading" className="space-y-4">
        <h2 id="accuracy-heading" className="text-xl font-semibold text-slate-900">
          4. Accuracy &amp; Data Quality Disclaimer
        </h2>
        <p className="text-sm leading-relaxed text-slate-700">
          While Prospect implements strict deterministic validation, provenance tracking, and
          decimal-safe arithmetic:
        </p>
        <ul className="list-disc space-y-1.5 pl-5 text-sm text-slate-700">
          <li>
            PDF parsing, table recognition, and OCR extraction are subject to layout ambiguities,
            non-standard font encodings, and visual distortions in source documents;
          </li>
          <li>
            Source filings may express units ambiguously (e.g. thousands vs. millions of currency
            units) or restate comparative figures across reporting periods;
          </li>
          <li>
            Prospect does not warrant that extraction results are 100% accurate, complete, reliable,
            or error-free. The service is provided on an <strong>&ldquo;AS IS&rdquo;</strong> and{" "}
            <strong>&ldquo;AS AVAILABLE&rdquo;</strong> basis without warranties of any kind.
          </li>
        </ul>
      </section>

      {/* 5. User Responsibilities & Content Ownership */}
      <section aria-labelledby="content-heading" className="space-y-4">
        <h2 id="content-heading" className="text-xl font-semibold text-slate-900">
          5. Uploaded Content &amp; Ownership Rights
        </h2>
        <div className="space-y-3 text-sm leading-relaxed text-slate-700">
          <p>
            <strong>You Retain Ownership of Your Documents:</strong> You retain all pre-existing
            copyright, title, and ownership rights to documents you upload to Prospect. Prospect
            does NOT claim ownership, title, or perpetual commercial rights over your uploaded
            financial filings.
          </p>
          <p>
            <strong>Limited Operational License:</strong> By uploading a document, you grant
            Prospect only a limited, non-exclusive, revocable, royalty-free license strictly
            necessary to receive, store, process, parse, extract, compute, display, export, and
            delete the document and derived figures solely to provide the service to you in your
            session.
          </p>
          <p>
            <strong>Your Authority to Upload:</strong> You represent and warrant that:
          </p>
          <ul className="list-disc space-y-1 pl-5">
            <li>You have the legal right, power, and authority to upload each document;</li>
            <li>
              Your document does not infringe any third party&rsquo;s copyright, trademark, trade
              secret, or intellectual property rights;
            </li>
            <li>
              You will not upload documents that violate applicable non-disclosure agreements, data
              privacy restrictions, or confidentiality obligations.
            </li>
          </ul>
        </div>
      </section>

      {/* 6. Acceptable Use */}
      <section aria-labelledby="acceptable-use-heading" className="space-y-4">
        <h2 id="acceptable-use-heading" className="text-xl font-semibold text-slate-900">
          6. Acceptable Use &amp; Platform Integrity
        </h2>
        <p className="text-sm leading-relaxed text-slate-700">
          You agree not to abuse, compromise, or disrupt the service. In particular, you must not
          upload malicious code, attempt unauthorized cross-session access, exceed rate limits, or
          exploit PDF parser vulnerabilities. Detailed rules are set forth in our{" "}
          <Link href="/acceptable-use" className="text-slate-900 underline hover:text-slate-700">
            Acceptable Use Policy
          </Link>
          .
        </p>
      </section>

      {/* 7. Service Availability & Modification */}
      <section aria-labelledby="availability-heading" className="space-y-4">
        <h2 id="availability-heading" className="text-xl font-semibold text-slate-900">
          7. Availability &amp; Service Continuity
        </h2>
        <p className="text-sm leading-relaxed text-slate-700">
          Prospect does not guarantee uninterrupted, continuous, or error-free availability. The
          operator reserves the right to modify, suspend, rate-limit, or terminate access to any
          part of the platform at any time for maintenance, security remediation, or resource
          management. Workspaces that remain inactive past their retention schedule are deleted
          automatically.
        </p>
      </section>

      {/* 8. Limitation of Liability */}
      <section aria-labelledby="liability-heading" className="space-y-4">
        <h2 id="liability-heading" className="text-xl font-semibold text-slate-900">
          8. Limitation of Liability
        </h2>
        <div className="rounded-md border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700 space-y-2">
          <p>
            To the maximum extent permitted by applicable law, neither the operator, developers, nor
            infrastructure providers of Prospect shall be liable for any indirect, incidental,
            special, consequential, or punitive damages, or any loss of profits, investment losses,
            trading losses, data loss, or business interruption arising out of or related to your
            use of or inability to use the platform.
          </p>
          <p className="text-xs text-slate-500">
            <strong>Statutory Terms Pending Review:</strong> Specific statutory damage caps and
            liability provisions must be finalized by the platform operator:{" "}
            <span className="font-mono text-amber-700 bg-amber-100/60 px-1 py-0.5 rounded">
              [REQUIRES HUMAN INPUT — FORMAL LIABILITY TERMS]
            </span>
            .
          </p>
        </div>
      </section>

      {/* 9. Age & Eligibility */}
      <section aria-labelledby="eligibility-heading" className="space-y-4">
        <h2 id="eligibility-heading" className="text-xl font-semibold text-slate-900">
          9. Eligibility
        </h2>
        <p className="text-sm leading-relaxed text-slate-700">
          Use of Prospect is subject to applicable legal age and capacity requirements:{" "}
          <span className="font-mono text-amber-700 bg-amber-100/60 px-1.5 py-0.5 rounded text-xs">
            [REQUIRES HUMAN DECISION — AGE / ELIGIBILITY POLICY]
          </span>
          .
        </p>
      </section>

      {/* 10. Governing Law */}
      <section aria-labelledby="law-heading" className="space-y-4">
        <h2 id="law-heading" className="text-xl font-semibold text-slate-900">
          10. Governing Law &amp; Jurisdiction
        </h2>
        <p className="text-sm leading-relaxed text-slate-700">
          These Terms shall be governed by and construed in accordance with the laws of:{" "}
          <span className="font-mono text-amber-700 bg-amber-100/60 px-1.5 py-0.5 rounded text-xs">
            [REQUIRES HUMAN INPUT — GOVERNING LAW AND JURISDICTION]
          </span>
          , without regard to conflict of law principles. Any dispute arising under these Terms
          shall be resolved exclusively in the designated courts of that jurisdiction.
        </p>
      </section>

      {/* 11. Contact */}
      <section aria-labelledby="contact-heading" className="space-y-4">
        <h2 id="contact-heading" className="text-xl font-semibold text-slate-900">
          11. Contact &amp; Inquiries
        </h2>
        <p className="text-sm leading-relaxed text-slate-700">
          For questions regarding these Terms of Use, please reach out to:{" "}
          <span className="font-mono text-amber-700 bg-amber-100/60 px-1.5 py-0.5 rounded text-xs">
            [REQUIRES HUMAN INPUT — OPERATOR CONTACT EMAIL]
          </span>
          .
        </p>
      </section>

      {/* Footer Navigation */}
      <footer className="border-t border-slate-200 pt-6 text-xs text-slate-500 flex flex-wrap gap-4">
        <Link href="/privacy" className="underline hover:text-slate-800">
          Privacy Policy
        </Link>
        <Link href="/acceptable-use" className="underline hover:text-slate-800">
          Acceptable Use Policy
        </Link>
        <Link href="/security" className="underline hover:text-slate-800">
          Security Disclosure
        </Link>
        <Link href="/copyright" className="underline hover:text-slate-800">
          Copyright &amp; IP
        </Link>
      </footer>
    </article>
  );
}
